const C=window.MYSOCIAL_CONFIG||{},SB=C.SUPABASE_URL&&C.SUPABASE_ANON_KEY?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const S={user:null,profile:null,users:[],posts:[],following:new Set(),likes:new Set(),mode:"login"};
const $=x=>document.getElementById(x), esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(x){let t=$("toast");t.textContent=x;t.style.display="block";setTimeout(()=>t.style.display="none",2200)}
function av(u,cls="avatar"){return `<div class="${cls}">${u?.avatar_url?`<img src="${esc(u.avatar_url)}">`:"🙂"}</div>`}
async function boot(){if(SB){let {data:{session}}=await SB.auth.getSession();if(session){await load(session.user);openApp()}else openAuth();SB.auth.onAuthStateChange(async(_,s)=>{if(s){await load(s.user);openApp()}else openAuth()})}else{let id=localStorage.getItem("ms_id");if(id){S.user=JSON.parse(localStorage.getItem("ms_user"));S.profile=S.user;S.users=JSON.parse(localStorage.getItem("ms_users")||"[]");S.posts=JSON.parse(localStorage.getItem("ms_posts")||"[]");openApp()}else openAuth()}bind()}
function openAuth(){$("authScreen").classList.remove("hidden");$("app").classList.add("hidden")}
function openApp(){$("authScreen").classList.add("hidden");$("app").classList.remove("hidden");renderStories();renderFeed();show("home")}
async function load(u){S.user=u;let p=await SB.from("profiles").select("*").eq("id",u.id).single();S.profile=p.data;if(!p.data){await SB.from("profiles").insert({id:u.id,username:(u.email||"user").split("@")[0],display_name:u.user_metadata?.name||"MySocial User"});S.profile=(await SB.from("profiles").select("*").eq("id",u.id).single()).data}S.users=(await SB.from("profiles").select("*").limit(200)).data||[];S.posts=(await SB.from("posts").select("*,profiles:author_id(*)").order("created_at",{ascending:false}).limit(100)).data||[];let f=await SB.from("follows").select("following_id").eq("follower_id",u.id);S.following=new Set((f.data||[]).map(x=>x.following_id));let l=await SB.from("likes").select("post_id").eq("user_id",u.id);S.likes=new Set((l.data||[]).map(x=>x.post_id))}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("name").classList.toggle("hidden",S.mode!=="signup");$("authBtn").textContent=S.mode==="signup"?"Create account":"Login"});$("authForm").onsubmit=auth;document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));$("newPost").onclick=()=>openPost();$("quickPost").onclick=()=>makePost($("quickText").value);$("search").oninput=search;window.toggleFollow=toggleFollow;window.toggleLike=toggleLike;window.viewUser=viewUser;window.editMe=editMe;window.logout=logout}
async function auth(e){e.preventDefault();let email=$("email").value.trim(),pw=$("password").value;if(SB){let r=S.mode==="signup"?await SB.auth.signUp({email,password:pw,options:{data:{name:$("name").value.trim()}}}):await SB.auth.signInWithPassword({email,password:pw});if(r.error)toast(r.error.message);else if(S.mode==="signup")toast("Account created. Check email if confirmation is enabled.")}else{let us=JSON.parse(localStorage.getItem("ms_users")||"[]");if(S.mode==="signup"){if(us.some(u=>u.email===email))return toast("Email already exists");let u={id:crypto.randomUUID(),email,name:$("name").value.trim()||email.split("@")[0],username:email.split("@")[0],avatar_url:""};us.push(u);localStorage.setItem("ms_users",JSON.stringify(us));localStorage.setItem("ms_user",JSON.stringify(u));localStorage.setItem("ms_id",u.id);S.user=S.profile=u;S.users=us;openApp()}else{let u=us.find(x=>x.email===email);if(!u)return toast("Account not found. Create one first.");localStorage.setItem("ms_user",JSON.stringify(u));localStorage.setItem("ms_id",u.id);S.user=S.profile=u;S.users=us;openApp()}}}
function show(p){["home","explore","profile","alerts","messages"].forEach(x=>$(x).classList.toggle("hidden",x!==p));if(p==="home")renderFeed();if(p==="explore")search();if(p==="profile")viewUser(S.user.id);if(p==="alerts")$("alertsBox").innerHTML='<div class="notice">Notifications are ready for the database layer.</div>'}
function renderStories(){$("stories").innerHTML=[["You","🙂"],["Rahul","😎"],["Priya","👩"],["Aman","🔥"],["Gamer","🎮"]].map(x=>`<div class="story"><div class="ring"><div>${x[1]}</div></div>${x[0]}</div>`).join("")}
function renderFeed(){$("feed").innerHTML=S.posts.length?S.posts.map(p=>{let u=p.profiles||S.users.find(x=>x.id===p.author_id)||S.profile;return `<article class="post"><div class="head">${av(u)}<div class="grow"><b>${esc(u?.display_name||u?.username)}</b><div class="small muted">${new Date(p.created_at).toLocaleString()}</div></div></div><div class="postbody">${esc(p.body)}</div><div class="actions"><button class="${S.likes.has(p.id)?"on":""}" onclick="toggleLike('${p.id}')">♥ Like</button><button onclick="toast('Comments module ready')">💬 Comment</button><button onclick="navigator.clipboard?.writeText(location.href);toast('Link copied')">↗ Share</button></div></article>`}).join(""):'<div class="card">No posts yet. Create the first post.</div>'}
async function makePost(body){body=body.trim();if(!body)return;if(SB){let r=await SB.from("posts").insert({author_id:S.user.id,body});if(r.error)return toast(r.error.message);await load(S.user)}else{let p={id:crypto.randomUUID(),author_id:S.user.id,body,created_at:new Date().toISOString(),profiles:S.user};S.posts.unshift(p);localStorage.setItem("ms_posts",JSON.stringify(S.posts))}$("quickText").value="";renderFeed();toast("Posted ✓")}
function openPost(){$("postBody").value="";$("postDialog").showModal();$("publish").onclick=e=>{e.preventDefault();makePost($("postBody").value);$("postDialog").close()}}
async function toggleLike(id){if(SB){if(S.likes.has(id))await SB.from("likes").delete().eq("post_id",id).eq("user_id",S.user.id);else await SB.from("likes").insert({post_id:id,user_id:S.user.id})}S.likes.has(id)?S.likes.delete(id):S.likes.add(id);renderFeed()}
function search(){let q=($("search").value||"").toLowerCase();let us=S.users.filter(u=>(u.display_name||"").toLowerCase().includes(q)||(u.username||"").toLowerCase().includes(q));$("users").innerHTML=us.map(u=>`<div class="user">${av(u)}<div class="grow"><b>${esc(u.display_name||u.username)}</b><div class="small muted">@${esc(u.username)}</div></div>${u.id!==S.user.id?`<button class="follow ${S.following.has(u.id)?"following":""}" onclick="toggleFollow('${u.id}')">${S.following.has(u.id)?"Following":"Follow"}</button>`:""}</div>`).join("")||'<div class="card">No users found.</div>'}
async function toggleFollow(id){if(SB){if(S.following.has(id))await SB.from("follows").delete().eq("follower_id",S.user.id).eq("following_id",id);else await SB.from("follows").insert({follower_id:S.user.id,following_id:id})}S.following.has(id)?S.following.delete(id):S.following.add(id);search();if($("profile").classList.contains("hidden")===false)viewUser(id)}
async function viewUser(id){let u=S.users.find(x=>x.id===id)||S.profile||S.user;let posts=S.posts.filter(p=>p.author_id===id);$("profileBox").innerHTML=`<div class="profile"><div class="profilehead">${av(u,"big")}<div class="grow"><h2>${esc(u.display_name||u.username)}</h2><div class="muted">@${esc(u.username||"user")}</div><div class="stats"><span><b>${posts.length}</b>Posts</span><span><b>0</b>Followers</span><span><b>${S.following.size}</b>Following</span></div></div></div><div class="bio">${esc(u.bio||"Welcome to MySocial 🚀")}</div>${id===S.user.id?`<button class="follow" onclick="editMe()">Edit profile</button> <button class="follow following" onclick="logout()">Logout</button>`:`<button class="follow ${S.following.has(id)?"following":""}" onclick="toggleFollow('${id}')">${S.following.has(id)?"Following":"Follow"}</button>`}</div>${posts.map(p=>`<article class="post"><div class="postbody">${esc(p.body)}</div></article>`).join("")}`}
function editMe(){let n=prompt("Name",S.profile.display_name||"");if(n===null)return;if(SB)SB.from("profiles").update({display_name:n}).eq("id",S.user.id).then(()=>load(S.user));else{S.profile.display_name=n;localStorage.setItem("ms_user",JSON.stringify(S.profile));localStorage.setItem("ms_users",JSON.stringify(S.users.map(x=>x.id===S.user.id?S.profile:x)))}viewUser(S.user.id);toast("Profile saved ✓")}
async function logout(){if(SB)await SB.auth.signOut();localStorage.clear();openAuth()}
boot();